/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/seed.component';
import * as i2 from '../../src/seed.service';
const styles_SeedComponent:any[] = ([] as any[]);
export const RenderType_SeedComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_SeedComponent,data:{}});
export function View_SeedComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(0,(null as any),['','']))],(null as any),(_ck,
      _v) => {
    var _co:i1.SeedComponent = _v.component;
    const currVal_0:any = _co.greeting;
    _ck(_v,0,0,currVal_0);
  });
}
export function View_SeedComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'seed-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_SeedComponent_0,
      RenderType_SeedComponent)),i0.ɵdid(1,114688,(null as any),0,i1.SeedComponent,
      [i2.SeedService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SeedComponentNgFactory:i0.ComponentFactory<i1.SeedComponent> = i0.ɵccf('seed-component',
    i1.SeedComponent,View_SeedComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlzL0RvY3VtZW50cy9HaXQvYW5ndWxhci1ucG0tbW9kdWxlLXNlZWQtbWFzdGVyL3NyYy9zZWVkLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9jaHJpcy9Eb2N1bWVudHMvR2l0L2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvc2VlZC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9jaHJpcy9Eb2N1bWVudHMvR2l0L2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvc2VlZC5jb21wb25lbnQudHMuU2VlZENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvY2hyaXMvRG9jdW1lbnRzL0dpdC9hbmd1bGFyLW5wbS1tb2R1bGUtc2VlZC1tYXN0ZXIvc3JjL3NlZWQuY29tcG9uZW50LnRzLlNlZWRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJ7e2dyZWV0aW5nfX0iLCI8c2VlZC1jb21wb25lbnQ+PC9zZWVkLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7OztJQUFBO0lBQUE7Ozs7b0JDQUE7TUFBQTs4QkFBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
